apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-productos-deployment-port2
  labels:
    app: ms-productos-port2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-productos-port2
  template:
    metadata:
      labels:
        app: ms-productos-port2
    spec:
      containers:
      - name: ms-productos
        image: maylinjg/ms-producto-fri:latest
        ports:
        - containerPort: 9081
        envFrom:
        - configMapRef:
            name: ms-productos-config-port2
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
